package util

enum class CurrencyCode(
    val country: String,
) {
    AED("United Arab Emirates"),
    AFN("Afghanistan"),
    ALL("Albania"),
    AMD("Armenia"),
    ANG("Netherlands"),
    AOA("Angola"),
    ARS("Argentina"),
    AUD("Australia"),
    AZN("Azerbaijan"),
    BAM("Bosnia and Herzegovina"),
    BBD("Barbados"),
    BDT("Bangladesh"),
    BGN("Bulgaria"),
    BHD("Bahrain"),
    BMD("Bermuda"),
    BOB("Bolivia"),
    BRL("Brazil"),
    BSD("Bahamas"),
    BTN("Bhutan"),
    BWP("Botswana"),
    BYN("Belarus"),
    BZD("Belize"),
    CAD("Canada"),
    CDF("Democratic Republic of Congo"),
    CHF("Switzerland"),
    CLF("Chile (Unidad de Fomento)"),
    CLP("Chile"),
    CNY("China"),
    COP("Colombia"),
    CRC("Costa Rica"),
    CUC("Cuba (Convertible Peso)"),
    CUP("Cuba (Cuban Peso)"),
    CVE("Cape Verde"),
    CZK("Czech Republic"),
    DJF("Djibouti"),
    DKK("Denmark"),
    DOP("Dominican Republic"),
    DZD("Algeria"),
    EGP("Egypt"),
    ERN("Eritrea"),
    ETB("Ethiopia"),
    EUR("European Union"),
    FJD("Fiji"),
    FKP("Falkland Islands"),
    GBP("United Kingdom"),
    GEL("Georgia"),
    GGP("Guernsey"),
    GHS("Ghana"),
    GIP("Gibraltar"),
    GMD("Gambia"),
    GNF("Guinea"),
    GTQ("Guatemala"),
    GYD("Guyana"),
    HKD("Hong Kong"),
    HNL("Honduras"),
    HRK("Croatia"),
    HTG("Haiti"),
    HUF("Hungary"),
    IDR("Indonesia"),
    ILS("Israel"),
    IMP("Isle of Man"),
    INR("India"),
    IQD("Iraq"),
    IRR("Iran"),
    ISK("Iceland"),
    JEP("Jersey"),
    JMD("Jamaica"),
    JOD("Jordan"),
    JPY("Japan"),
    KES("Kenya"),
    KGS("Kyrgyzstan"),
    KHR("Cambodia"),
    KMF("Comoros"),
    KPW("North Korea"),
    KRW("South Korea"),
    KWD("Kuwait"),
    KZT("Kazakhstan"),
    LAK("Laos"),
    LBP("Lebanon"),
    LKR("Sri Lanka"),
    LRD("Liberia"),
    LSL("Lesotho"),
    LTL("Lithuania"),
    LYD("Libya"),
    MAD("Morocco"),
    MDL("Moldova"),
    MGA("Madagascar"),
    MKD("North Macedonia"),
    MMK("Myanmar"),
    MNT("Mongolia"),
    MOP("Macao"),
    MRO("Mauritania"),
    MRU("Mauritius"),
    MUR("Mauritius"),
    MVR("Maldives"),
    MWK("Malawi"),
    MXN("Mexico"),
    MYR("Malaysia"),
    MZN("Mozambique"),
    NAD("Namibia"),
    NGN("Nigeria"),
    NIO("Nicaragua"),
    NOK("Norway"),
    NPR("Nepal"),
    NZD("New Zealand"),
    OMR("Oman"),
    PAB("Panama"),
    PGK("Papua New Guinea"),
    PHP("Philippines"),
    PKR("Pakistan"),
    PLN("Poland"),
    PYG("Paraguay"),
    QAR("Qatar"),
    RON("Romania"),
    RSD("Serbia"),
    RUB("Russia"),
    RWF("Rwanda"),
    SAR("Saudi Arabia"),
    SBD("Solomon Islands"),
    SCR("Seychelles"),
    SDG("Sudan"),
    SEK("Sweden"),
    SGD("Singapore"),
    SLL("Sierra Leone"),
    SOS("Somalia"),
    SRD("Suriname"),
    STD("São Tomé and Príncipe"),
    STN("São Tomé and Príncipe"),
    SVC("El Salvador"),
    SYP("Syria"),
    THB("Thailand"),
    TJS("Tajikistan"),
    TMT("Turkmenistan"),
    TND("Tunisia"),
    TOP("Tonga"),
    TRY("Türkiye"),
    TTD("Trinidad and Tobago"),
    TWD("Taiwan"),
    TZS("Tanzania"),
    UAH("Ukraine"),
    USD("United States of America"),
    UZS("Uzbekistan"),
    VES("Venezuela"),
    VND("Vietnam"),
    VUV("Vanuatu"),
    WST("Samoa"),
    XAF("Central African Republic"),
    YER("Yemen"),
    ZAR("South Africa"),
    ZMW("Zambia"),
    ZWL("Zimbabwe"),
}
